name: "airbnb-clone"

services:
  postgres:
    container_name: postgrescontainer
    image: 'postgres:latest'
    restart: always
    volumes:
      - postgresvolume:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    expose:
      - 5432
    ports:
      - 5432:5432

networks:
  yvolabs:
    driver: bridge

volumes:
  postgresvolume: